language: node_js
node_js:
- 8
script:
- npm run lint
- npm run test-ci
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: CCn2Ytj+lP4OdcmjcDnWJBpOMKpkZhVxLbq+sl2VktEUDwXkzwwokVgBXElG6LDMhmC7wTlUOHkKzMKVKLZ501HlfZWEGKDb4J+ZRSfA1jN9enDWZxLyykYbGEjZZCSXyRJSzSohv81lCBedl+/K/gS5wl5IpHAnCaHuJYmHK4qhy4fd8k59cIt5iQMs+6Yg+npU0aLFi550j8OVnQWSyOp7Lw1BtaLZ4LJUDoqwBjSWmn6oFYHCOjQJ6fklo0Sk+Cupwn6zSk1E3CyByfk+xqXuG/9Sj/e7kvNE3DANk57ON0hewFit0yJybrf8KQDK4zFy83ZFR8KEmueOEDfTRPf3g2P8K+4iQNCEzRJ2ZYXjjHVcJ4Ag3EVyBPWIiud4cnrQJ8v+Fx9LmI8++HciWVOHiV1E4U6VAKJ8tEepH2Huruj2NbVkB732kjeims8clYzJMKFvFbkYl2HkVlLaJL1TmUpLP6DJe9YLxmBSA9CEqBYRZf/V5VyASLdUWB36pmNJjVpzln6vdTosURdmJvWd5TDb53qKy5dmvG0o6579C0k3O1r0TJBvHxwV5eT0Qx8Cu36dtdgaQMyNQhgkRfz7/Kvhgjh/hemynOasuNHfEibUTbw0N2q1U4qPlrvIS4AiV63LBzFasj/Pla0zXFVqvFEi3LDJ3hXlDoGI09s=
  app: din-din
  on:
    repo: flyiniggle/DinDinWebUI
