language: node_js
node_js:
- 9
jobs:
  include:
    - stage: test
      env: 
        - NODE_ENV=development
      script:
        - npm run lint
        - npm run test-ci
    - stage: build staging
      env: 
        - NODE_ENV=production
        - API_ROOT=https://dindinwebapi-staging.herokuapp.com/
      script:
        - npm run build
      deploy:
        provider: heroku
        api_key:
          secure: BQNRTrqP6BVipaRKNFF8XSR2piGjoSWaV2iM6tnGpAp1I8l3td8Io96yLTcUjypEOuwKHJzuyW/e7MKOgt21A1xSZwfA8GQigbx246FzCXdwU1XfewyTUp2fyGnEEFVpamXEg56DMZLeYKZeKMWAhGO1nobW/271psZgxAPUqOym0YPOqzovpnXJBVfTjj3GvZbEp400vaRBjnDVBP3sAR1mV/+z/3ig7YQN/AqJ2SGDho6S0UXtHbXp0R395f9CiueVSbb3HimoCyHJg7S8xgx7n0aer9Ggocy2vrN2ihGUidcdyP1hbt5XhWRtAAB3tdRs552S/5+c2zidRkjGp2bHDKbYDAm3oks8WnT7+Ci/VJDt7WI7JxhixwO2HCPkCTmhx5uVwL6VayzGUIdRE9+a5aAcmlYJUEONM3bkURA8xRUD21Vn58MaMXhSVjTwqHDE81qGgYMofA7DIftlRlwIKDWQTuZH3kDMxfAEXKby6KkksrpY3RqW1T84jlSdRutHBpEBBxdzbkKxQ53XqRExdhC8mLvwkymziVhGODX2sWw3k0ZBE2RlKMpwxwAi0+Odst3WQ3Yh4mtJuGbUSNr1VSIrn52lNY/J1u94sygTh8QJXYOkTTCngGVd+q/kogulNLf7zIzM8Po93YIx9Llsbi+6FFne4UAbLpehV0o=
        app: din-din-staging
        on:
          repo: flyiniggle/DinDinWebUI
          branch: master
    - stage: build live
      env: 
        - NODE_ENV=production
        - API_ROOT=https://dindinwebapi.herokuapp.com
      script:
        - npm run build
      deploy:
        provider: heroku
        api_key:
          secure: BQNRTrqP6BVipaRKNFF8XSR2piGjoSWaV2iM6tnGpAp1I8l3td8Io96yLTcUjypEOuwKHJzuyW/e7MKOgt21A1xSZwfA8GQigbx246FzCXdwU1XfewyTUp2fyGnEEFVpamXEg56DMZLeYKZeKMWAhGO1nobW/271psZgxAPUqOym0YPOqzovpnXJBVfTjj3GvZbEp400vaRBjnDVBP3sAR1mV/+z/3ig7YQN/AqJ2SGDho6S0UXtHbXp0R395f9CiueVSbb3HimoCyHJg7S8xgx7n0aer9Ggocy2vrN2ihGUidcdyP1hbt5XhWRtAAB3tdRs552S/5+c2zidRkjGp2bHDKbYDAm3oks8WnT7+Ci/VJDt7WI7JxhixwO2HCPkCTmhx5uVwL6VayzGUIdRE9+a5aAcmlYJUEONM3bkURA8xRUD21Vn58MaMXhSVjTwqHDE81qGgYMofA7DIftlRlwIKDWQTuZH3kDMxfAEXKby6KkksrpY3RqW1T84jlSdRutHBpEBBxdzbkKxQ53XqRExdhC8mLvwkymziVhGODX2sWw3k0ZBE2RlKMpwxwAi0+Odst3WQ3Yh4mtJuGbUSNr1VSIrn52lNY/J1u94sygTh8QJXYOkTTCngGVd+q/kogulNLf7zIzM8Po93YIx9Llsbi+6FFne4UAbLpehV0o=
        app: din-din
        on:
          repo: flyiniggle/DinDinWebUI
          tags: true
