language: node_js
node_js:
- 8
script:
- npm run lint
- npm run test-ci
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: HskXykDorKc3BQxzf/ryoERvDSkZS61y9bQYLYqwhgudO8kXPskQsOnVnkm/5N5/9ViL4lJT4QtAx0QQAJwKRoK0XjhrEI/Iol6hxAmcDfqphApePQZnN2ZrnhZc5arA+KwipEP46Vn0vZRNh5kTzyBnSuzYhwisccALbJHN3gEs6zzln31S0maJAM7irReVVPSB/8pzjVzk1ZgDO4bpC7m1/DrE19VtYoWPgovMgS6Vpt1oLt8cSS393ajzGaUi6DeOo8vWsj98OUzPq35QZZqgYqAavSj6dHilZPEv6D62IG2MXQl+ugdiiW8QZtq5bNimGbB9kEb/ccX1mlwgXJt0RBmhQjToGutY6N+IpMk+R45uunWSeX6zh9+/N7tfRhJFLqBL3Hhi1NG3gHemcU09sHXeKIvjcQEhFk9zmpIJ59ZI/hp8bzJ1YtJx+txSIejNh8e9ErcCgZa+AJliBrV6osGp+jOeldOe/nwxEhw/Oof3HdtJ1VnBv8SdyLXu2EIf0woQQu+LtPS/XcBo7EwvR7C3Av38sIhxLhG5jS/pQ18oFsUKCZ/pCLN6v8/KR9uuHCbjKktCaCujsVJFUQbJF79JP7brCCgcNgOzioEefrpYCxsh280g3GfP9T5OGhWaTBe+A8e8nnxDUJwA3hjDuG9M7JxyajMGyZBlQTg=
  app: din-din
  on:
    repo: flyiniggle/DinDinWebUI
