language: node_js
node_js:
- 8
script:
- npm run lint
- npm run test-ci
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: 0qXMXxbL4v1RPR1nlUTHZRzE2yYUc8meOyzJAq4u1Uj5Bg9XHlmWfpCgLVjtrga6/yC7YHqrGtPB9hlXntixdSBnU1TbaFoMiGkevDw6YmMS+P2xLFsIyCod5w1Qv+4Dpc6++WiJDNUK1o8oHsa+OlOA04OOCruA6HAAGrUXQdkpUZR7p4zZ8eDkuqnMMMa2eBHxDh7sGPqLRnArLxA+RvNv97evdT7lPmnkJv9ODQNk6XVZse4rgaGxWbg71TV5A619jabQrgrew1FBiksH5griP8dhh+g0qInA99NCQAVf2UImJ4UfpxnJMpf/1MQnU2iEq9OVzPf/OLG4LCSD3RdM50tFAjpyNFgrbqXPWrAO5O65VT6XYA+OXMihfbijLXAhXUleBYnpVjg+DX5Hk4Fnx9zcdaTVXkKeoaJ8HNP1A78+1i7W1rM4K+EHeiCN6fppEfcuqbVUaX8ceZ5HAm1Z8vjWWWggzCPlIzXYDxqh1GZIx8MGXv0Mh1g3kuGiym471FS3xI8T4+wB6x/3GIL2KoceVF+haiGThqVeXohPqpUtSxWClrvv20drTxIAPTej2U4zraWiLsTgapNxRMzWkJjxrOjiMh4HsN13At2H+0VQvRlUmaYSAl81kZ9Co50zXunfyt4UUZg4L2Joa8V4w+0kZ10il/vBWWDKUsY=
  app: din-din
  on:
    repo: flyiniggle/DinDinWebUI
