language: node_js
node_js:
- 8
script:
- npm run lint
- npm run test-ci
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: NCazyJi4n4nknTc1TybN76TYeG9NZyetARP8L6KaWIL4TecdexNifRceYnEbhp5wlEu9k+lKBaiIp+8VukOXjV2RPyx0mrR5p/pjHVXPrRKa/Fcbn2YqS4dWmSZdqF/6PX08P9wCa9KjokyaSZE9rTOQkJQNBn6XWAiYQgVYVr6SI2w4U5U1YAoF4i/k9oxXV4U45SIp6Xg32ELche2OF5BxuxFSzmHSCce4nDs/0/EXWA2hPXDrPX3sScxa2kx9sC1I4avyJqBLraKiLRFaQddXoVZrekNZZhEXqQDPu1a/Cc+xR97ina5ivX5iP2Z+Xj8zCSY9d0zCGHF7eDQrzZLUFl7Km/6DjaBo5tc0WgU1ZHX8MiXyt6kJO4RvkDmQkgNBJZOpFwxb3G8DXdZmzD+hu292NZ/Y55sdQ7AgePDmk80uYIYwn7aQgxzZvFhnDCJLmc7Sl2ezdps1IGFT1RnxCqdB3f6TweYKOn9/eQn6Cl+vGwCBFTjJG/TF6TJb5Erxt5OpAcAfuJjNWYi7sSZeQ1aRtrVUo+Vi4gcez6QkhktWf9Ityn7sF1NmW5B2o2GsnbtrFRgrCE+kFHF1bdRTzsUYlQzetlGM8/2oyRvGzYkCaHuXFgFMk0G2DZqXN9laQgOjUacDsrTW2tq8Boh8gJKZ3TpdTpFFevm/6TY=
  app: din-din
  on:
    repo: flyiniggle/DinDinWebUI
